set_property PACKAGE_PIN P34 [get_ports {pcie0_exp_rxn[0]}]
set_property PACKAGE_PIN M34 [get_ports {pcie0_exp_rxn[1]}]
set_property PACKAGE_PIN K34 [get_ports {pcie0_exp_rxn[2]}]
set_property PACKAGE_PIN H34 [get_ports {pcie0_exp_rxn[3]}]
set_property PACKAGE_PIN P33 [get_ports {pcie0_exp_rxp[0]}]
set_property PACKAGE_PIN M33 [get_ports {pcie0_exp_rxp[1]}]
set_property PACKAGE_PIN K33 [get_ports {pcie0_exp_rxp[2]}]
set_property PACKAGE_PIN H33 [get_ports {pcie0_exp_rxp[3]}]
set_property PACKAGE_PIN N31 [get_ports {pcie0_exp_txn[0]}]
set_property PACKAGE_PIN L31 [get_ports {pcie0_exp_txn[1]}]
set_property PACKAGE_PIN J31 [get_ports {pcie0_exp_txn[2]}]
set_property PACKAGE_PIN G31 [get_ports {pcie0_exp_txn[3]}]
set_property PACKAGE_PIN N30 [get_ports {pcie0_exp_txp[0]}]
set_property PACKAGE_PIN L30 [get_ports {pcie0_exp_txp[1]}]
set_property PACKAGE_PIN J30 [get_ports {pcie0_exp_txp[2]}]
set_property PACKAGE_PIN G30 [get_ports {pcie0_exp_txp[3]}]
set_property PACKAGE_PIN F34 [get_ports {pcie1_exp_rxn[0]}]
set_property PACKAGE_PIN D34 [get_ports {pcie1_exp_rxn[1]}]
set_property PACKAGE_PIN B34 [get_ports {pcie1_exp_rxn[2]}]
set_property PACKAGE_PIN A32 [get_ports {pcie1_exp_rxn[3]}]
set_property PACKAGE_PIN F33 [get_ports {pcie1_exp_rxp[0]}]
set_property PACKAGE_PIN D33 [get_ports {pcie1_exp_rxp[1]}]
set_property PACKAGE_PIN B33 [get_ports {pcie1_exp_rxp[2]}]
set_property PACKAGE_PIN A31 [get_ports {pcie1_exp_rxp[3]}]
set_property PACKAGE_PIN E31 [get_ports {pcie1_exp_txn[0]}]
set_property PACKAGE_PIN D29 [get_ports {pcie1_exp_txn[1]}]
set_property PACKAGE_PIN C31 [get_ports {pcie1_exp_txn[2]}]
set_property PACKAGE_PIN B29 [get_ports {pcie1_exp_txn[3]}]
set_property PACKAGE_PIN E30 [get_ports {pcie1_exp_txp[0]}]
set_property PACKAGE_PIN D28 [get_ports {pcie1_exp_txp[1]}]
set_property PACKAGE_PIN C30 [get_ports {pcie1_exp_txp[2]}]
set_property PACKAGE_PIN B28 [get_ports {pcie1_exp_txp[3]}]
set_property PACKAGE_PIN M29 [get_ports {pci0_clk_clk_n}]
set_property PACKAGE_PIN M28 [get_ports {pci0_clk_clk_p}]
set_property PACKAGE_PIN H29 [get_ports {pci1_clk_clk_n}]
set_property PACKAGE_PIN H28 [get_ports {pci1_clk_clk_p}]
set_property PACKAGE_PIN K29 [get_ports {pci0_ext_clk_n}]
set_property PACKAGE_PIN K28 [get_ports {pci0_ext_clk_p}]
set_property PACKAGE_PIN F29 [get_ports {pci1_ext_clk_n}]
set_property PACKAGE_PIN F28 [get_ports {pci1_ext_clk_p}]
set_property IOSTANDARD LVTTL [get_ports {RST_NVME_*}]

create_clock -period 10.000 -name pci0_clk_clk_p -waveform {0.000 5.000} [get_ports pci0_clk_clk_p]
create_clock -period 10.000 -name pci1_clk_clk_p -waveform {0.000 5.000} [get_ports pci1_clk_clk_p]


set_property CLOCK_DELAY_GROUP PHY_CORE_CLK_GRP1 [get_nets -of [get_pins cpu_ep/cpu_subsys_EP0/xdma_0/inst/pcie4c_ip_i/inst/cpu_subsys_xdma_0_0_pcie4c_ip_pcie_4_0_pipe_inst/pcie_4_c_e4_inst/CORECLK]]
set_property CLOCK_DELAY_GROUP PHY_CORE_CLK_GRP1 [get_nets -of [get_pins cpu_ep/cpu_subsys_EP0/xdma_0/inst/pcie4c_ip_i/inst/cpu_subsys_xdma_0_0_pcie4c_ip_pcie_4_0_pipe_inst/pcie_4_c_e4_inst/PIPECLK]]

set_property CLOCK_DELAY_GROUP PHY_CORE_CLK_GRP2 [get_nets -of [get_pins cpu_ep/cpu_subsys_EP0/xdma_1/inst/pcie4c_ip_i/inst/cpu_subsys_xdma_1_0_pcie4c_ip_pcie_4_0_pipe_inst/pcie_4_c_e4_inst/CORECLK]]
set_property CLOCK_DELAY_GROUP PHY_CORE_CLK_GRP2 [get_nets -of [get_pins cpu_ep/cpu_subsys_EP0/xdma_1/inst/pcie4c_ip_i/inst/cpu_subsys_xdma_1_0_pcie4c_ip_pcie_4_0_pipe_inst/pcie_4_c_e4_inst/PIPECLK]]


set_property LOC BUFG_GT_X0Y131 [get_cells {cpu_ep/cpu_subsys_EP0/xdma_1/inst/pcie4c_ip_i/inst/cpu_subsys_xdma_1_0_pcie4c_ip_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/bufg_gt_pclk}]
set_property LOC BUFG_GT_X0Y124 [get_cells {cpu_ep/cpu_subsys_EP0/xdma_1/inst/pcie4c_ip_i/inst/cpu_subsys_xdma_1_0_pcie4c_ip_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/bufg_gt_coreclk}]
set_property LOC BUFG_GT_X0Y108 [get_cells {cpu_ep/cpu_subsys_EP0/xdma_0/inst/pcie4c_ip_i/inst/cpu_subsys_xdma_0_0_pcie4c_ip_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/bufg_gt_pclk}]
set_property LOC BUFG_GT_X0Y102 [get_cells {cpu_ep/cpu_subsys_EP0/xdma_0/inst/pcie4c_ip_i/inst/cpu_subsys_xdma_0_0_pcie4c_ip_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/bufg_gt_coreclk}]

set_property USER_CLOCK_ROOT X0Y5 [get_nets {cpu_ep/cpu_subsys_EP0/xdma_1/inst/pcie4c_ip_i/inst/cpu_subsys_xdma_1_0_pcie4c_ip_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/CLK_CORECLK}]
set_property USER_CLOCK_ROOT X0Y5 [get_nets {cpu_ep/cpu_subsys_EP0/xdma_1/inst/pcie4c_ip_i/inst/cpu_subsys_xdma_1_0_pcie4c_ip_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/CLK_PCLK2_GT}]
set_property USER_CLOCK_ROOT X0Y4 [get_nets {cpu_ep/cpu_subsys_EP0/xdma_0/inst/pcie4c_ip_i/inst/cpu_subsys_xdma_0_0_pcie4c_ip_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/CLK_CORECLK}]
set_property USER_CLOCK_ROOT X0Y4 [get_nets {cpu_ep/cpu_subsys_EP0/xdma_0/inst/pcie4c_ip_i/inst/cpu_subsys_xdma_0_0_pcie4c_ip_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/CLK_PCLK2_GT}]
