set_property PACKAGE_PIN AP8 [get_ports {BC_A_CLK}]
set_property PACKAGE_PIN AM5 [get_ports {BC_A_CS}]
set_property PACKAGE_PIN AP3 [get_ports {BC_A_LATCH}]
set_property PACKAGE_PIN AP2 [get_ports {BC_A_RXD}]
set_property PACKAGE_PIN AN5 [get_ports {BC_A_RXEN}]
set_property PACKAGE_PIN AP7 [get_ports {BC_A_TXD[0]}]
set_property PACKAGE_PIN AP6 [get_ports {BC_A_TXD[1]}]
set_property PACKAGE_PIN AP5 [get_ports {BC_A_TXD[2]}]
set_property PACKAGE_PIN AM6 [get_ports {BC_A_TXD[3]}]
set_property PACKAGE_PIN AN4 [get_ports {RF_TXEN_OUT[0]}]
set_property PACKAGE_PIN AD13 [get_ports {BC_B_CLK}]
set_property PACKAGE_PIN AG16 [get_ports {BC_B_CS}]
set_property PACKAGE_PIN AJ13 [get_ports {BC_B_LATCH}]
set_property PACKAGE_PIN AN14 [get_ports {BC_B_RXD}]
set_property PACKAGE_PIN AH15 [get_ports {BC_B_RXEN}]
set_property PACKAGE_PIN AN2  [get_ports {BC_B_TXD[0]}]
set_property PACKAGE_PIN AN1  [get_ports {BC_B_TXD[1]}]
set_property PACKAGE_PIN AP13 [get_ports {BC_B_TXD[2]}]
set_property PACKAGE_PIN AP12 [get_ports {BC_B_TXD[3]}]
set_property PACKAGE_PIN AL16 [get_ports {RF_TXEN_OUT[1]}]
set_property PACKAGE_PIN AN10 [get_ports {CLK_PL_SYS_N}]
set_property PACKAGE_PIN AM10 [get_ports {CLK_PL_SYS_P}]
set_property PACKAGE_PIN F9 [get_ports {FPGA_SYNC}]
#set_property PACKAGE_PIN F10 [get_ports {GPS_1PPS}]
#set_property PACKAGE_PIN K14 [get_ports {HDIO_B88_N[1]}]
#set_property PACKAGE_PIN B13 [get_ports {HDIO_B88_N[10]}]
#set_property PACKAGE_PIN A13 [get_ports {HDIO_B88_N[11]}]
#set_property PACKAGE_PIN A12 [get_ports {HDIO_B88_N[12]}]
#set_property PACKAGE_PIN H14 [get_ports {HDIO_B88_N[2]}]
#set_property PACKAGE_PIN J13 [get_ports {HDIO_B88_N[3]}]
#set_property PACKAGE_PIN G13 [get_ports {HDIO_B88_N[4]}]
#set_property PACKAGE_PIN F13 [get_ports {HDIO_B88_N[5]}]
#set_property PACKAGE_PIN F12 [get_ports {HDIO_B88_N[6]}]
#set_property PACKAGE_PIN D14 [get_ports {HDIO_B88_N[7]}]
#set_property PACKAGE_PIN D12 [get_ports {HDIO_B88_N[8]}]
#set_property PACKAGE_PIN C13 [get_ports {HDIO_B88_N[9]}]
#set_property PACKAGE_PIN K15 [get_ports {HDIO_B88_P[1]}]
#set_property PACKAGE_PIN C14 [get_ports {HDIO_B88_P[10]}]
#set_property PACKAGE_PIN A14 [get_ports {HDIO_B88_P[11]}]
#set_property PACKAGE_PIN B12 [get_ports {HDIO_B88_P[12]}]
#set_property PACKAGE_PIN H15 [get_ports {HDIO_B88_P[2]}]
#set_property PACKAGE_PIN J14 [get_ports {HDIO_B88_P[3]}]
#set_property PACKAGE_PIN H13 [get_ports {HDIO_B88_P[4]}]
#set_property PACKAGE_PIN F14 [get_ports {HDIO_B88_P[5]}]
#set_property PACKAGE_PIN G12 [get_ports {HDIO_B88_P[6]}]
#set_property PACKAGE_PIN E14 [get_ports {HDIO_B88_P[7]}]
#set_property PACKAGE_PIN E12 [get_ports {HDIO_B88_P[8]}]
#set_property PACKAGE_PIN D13 [get_ports {HDIO_B88_P[9]}]
#set_property PACKAGE_PIN A9 [get_ports {HDIO_B89_N3}]
#set_property PACKAGE_PIN A10 [get_ports {HDIO_B89_P3}]
set_property PACKAGE_PIN AD17 [get_ports {PL_DBG_LED}]
set_property PACKAGE_PIN AN8 [get_ports {PL_SPI_CS_N}]
set_property PACKAGE_PIN AN13 [get_ports {PL_SPI_MISO}]
set_property PACKAGE_PIN AN12 [get_ports {PL_SPI_MOSI}]
set_property PACKAGE_PIN AN7 [get_ports {PL_SPI_SCK}]
set_property PACKAGE_PIN K11 [get_ports {RF_A_LOCK}]
set_property PACKAGE_PIN J11 [get_ports {RF_A_RXCTL}]
set_property PACKAGE_PIN K10 [get_ports {RF_A_SWITCH}]
set_property PACKAGE_PIN J12 [get_ports {RF_A_TXEN}]
set_property PACKAGE_PIN H11 [get_ports {RF_A_UR_RX}]
set_property PACKAGE_PIN K12 [get_ports {RF_A_UR_TX}]
set_property PACKAGE_PIN D9 [get_ports {RF_B_LOCK}]
set_property PACKAGE_PIN G11 [get_ports {RF_B_RXCTL}]
set_property PACKAGE_PIN C9 [get_ports {RF_B_SWITCH}]
set_property PACKAGE_PIN H9 [get_ports {RF_B_TXEN}]
set_property PACKAGE_PIN G10 [get_ports {RF_B_UR_RX}]
set_property PACKAGE_PIN H10 [get_ports {RF_B_UR_TX}]
set_property PACKAGE_PIN C11 [get_ports {RF_A_TPM_1V0}]
set_property PACKAGE_PIN B11 [get_ports {RF_A_TNM_1V0}]
set_property PACKAGE_PIN C10 [get_ports {RF_B_TPM_1V0}]
set_property PACKAGE_PIN B10 [get_ports {RF_B_TNM_1V0}]
set_property PACKAGE_PIN T15 [get_ports {PL_VP}]
set_property PACKAGE_PIN U14 [get_ports {PL_VN}]

#set_property IOSTANDARD LVTTL [get_ports {HDIO_*}]
#set_property IOSTANDARD LVTTL [get_ports {GPS_1PPS}]
set_property IOSTANDARD LVTTL [get_ports {RF_*}]
set_property IOSTANDARD LVTTL [get_ports {FPGA_SYNC}]
set_property IOSTANDARD LVCMOS12 [get_ports {BC_*}]
set_property IOSTANDARD LVCMOS12 [get_ports {PL_SPI*}]
set_property IOSTANDARD LVCMOS12 [get_ports {PL_DBG_LED}]
set_property DRIVE 8 [get_ports {PL_SPI*}]
set_property DRIVE 8 [get_ports {PL_DBG_LED}]
set_property DRIVE 8 [get_ports {BC_*}]
set_property IOSTANDARD ANALOG [get_ports RF_A_TPM_1V0]
set_property IOSTANDARD ANALOG [get_ports RF_B_TPM_1V0]
set_property IOSTANDARD ANALOG [get_ports PL_VP]

#set_property IOSTANDARD DIFF_SSTL12 [get_ports CLK_PL_SYS_P]
set_property IOSTANDARD LVDS [get_ports CLK_PL_SYS_P]
create_clock -period 3.3333 -name {CLK_PL_SYS_P} -waveform {0.000 1.666} [get_ports {CLK_PL_SYS_P}]

#set_property PACKAGE_PIN H14 [get_ports {RST_GPS_N}]
#set_property PACKAGE_PIN J13 [get_ports {GPS_EVENT}]
#set_property PACKAGE_PIN A14 [get_ports {PPS_GPS_PL}]
#set_property PACKAGE_PIN J14 [get_ports {UART_PL_GPS}]
#set_property PACKAGE_PIN E12 [get_ports {UART_GPS_PL}]
#set_property PACKAGE_PIN G13 [get_ports {DBG_UART_TX}]
#set_property PACKAGE_PIN H13 [get_ports {DBG_UART_RX}]
#set_property PACKAGE_PIN H15 [get_ports {DBG_PPSOUT}]
#set_property PACKAGE_PIN E14 [get_ports {UART_IMU_PL}]


set_property PACKAGE_PIN D18 [get_ports {RST_GPS_N}]
set_property PACKAGE_PIN F10 [get_ports {PPS_GPS_PL}]
set_property PACKAGE_PIN A10 [get_ports {UART_PL_GPS}]
set_property PACKAGE_PIN A9 [get_ports {UART_GPS_PL}]
set_property PACKAGE_PIN E14 [get_ports {UART_IMU_PL}]

#J30J J64 PIN4
set_property PACKAGE_PIN AP12 [get_ports {DBG_UART_TX}] 
#J30J J64 PIN5
set_property PACKAGE_PIN AN14 [get_ports {DBG_UART_RX}]
#J30J J64 PIN7
set_property PACKAGE_PIN AL16 [get_ports {DBG_PPSOUT}]
set_property IOSTANDARD LVCMOS12 [get_ports {DBG_*}]
set_property DRIVE 8 [get_ports {DBG_*}]

set_property IOSTANDARD LVTTL [get_ports {UART_IMU_PL}]
#set_property IOSTANDARD LVTTL [get_ports {DBG_*}]
set_property IOSTANDARD LVTTL [get_ports {RST_GPS_N}]
set_property IOSTANDARD LVTTL [get_ports {GPS_EVENT}]
set_property IOSTANDARD LVTTL [get_ports {PPS_GPS_PL}]
set_property IOSTANDARD LVTTL [get_ports {UART_PL_GPS}]
set_property IOSTANDARD LVTTL [get_ports {UART_GPS_PL}]

set_property PULLDOWN true [get_ports {BC_B_RXD}]
set_property PULLDOWN true [get_ports {BC_B_RXD}]
set_property PULLDOWN true [get_ports {FPGA_SYNC}]

set_property PACKAGE_PIN F14 [get_ports {PL_RS422_3_TX}]
set_property PACKAGE_PIN K15 [get_ports {PL_RS422_3_RX}]
set_property PACKAGE_PIN B13 [get_ports {PL_RS422_1_TX}]
set_property PACKAGE_PIN B12 [get_ports {PL_RS422_1_RX}]
set_property PACKAGE_PIN A9 [get_ports {PL_RS422_2_RX}]
set_property PACKAGE_PIN C13 [get_ports {PL_RS422_SAR_1_TXD}]
set_property PACKAGE_PIN C14 [get_ports {PL_RS422_SAR_1_TXC}]
set_property PACKAGE_PIN D13 [get_ports {PL_RS422_SAR_2_TXD}]
set_property PACKAGE_PIN D14 [get_ports {PL_RS422_SAR_2_TXC}]
set_property IOSTANDARD LVTTL [get_ports {PL_RS422*}]

set_property PACKAGE_PIN E14 [get_ports {PL_RS485_M_TX}]
set_property PACKAGE_PIN A10 [get_ports {PL_RS485_M_DE_REN}]
set_property PACKAGE_PIN F13 [get_ports {PL_RS485_M_RX}]
set_property PACKAGE_PIN A12 [get_ports {PL_RS485_M_PO_0}]
set_property PACKAGE_PIN K14 [get_ports {PL_RS485_M_PO_1}]
set_property IOSTANDARD LVTTL [get_ports {PL_RS485*}]
